# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_group_controller
    - gripper_group_controller

  arm_group_controller:
    type: FollowJointTrajectory
    joints:
      - z_axis
      - link_1
      - link_2
      - link_3
      - wrist_1
      - gripper-wrist
    action_ns: follow_joint_trajectory
    default: true
  gripper_group_controller:
    type: FollowJointTrajectory
    joints:
      - claw1-slide
      - finger1-rotate
      - claw2-slide
      - finger2-rotate
    action_ns: follow_joint_trajectory
    default: true